server:
  port: 8081

spring:
  application:
    name: mini-jira

  datasource:
    url: jdbc:postgresql://localhost:5432/mini_jira
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      retries: 3
      properties:
        enable.idempotence: true

    consumer:
      group-id: mini-jira-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset: earliest
      properties:
        spring.json.trusted.packages: "*"

mini-jira:
  kafka:
    task-events-topic: task-events
    notification-events-topic: notification-events

  notification-service:
    url: http://localhost:8082

logging:
  level:
    com.minijira: INFO